# Generated by Django 5.1.7 on 2025-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_studentprofile_remarks'),
        ('teacher', '0002_alter_attendance_class_grade'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'class_grade', 'section', 'subject', 'date'), name='unique_attendance_per_student'),
        ),
    ]
