# Generated by Django 5.1.7 on 2025-04-02 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_attendance_unique_attendance_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
