# Generated by Django 5.1.7 on 2025-03-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_subject_alter_class_teacher_alter_section_teacher_and_more'),
        ('authentication', '0003_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='authentication.teacherprofile'),
        ),
    ]
