# Generated by Django 5.1.7 on 2025-03-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
    ]
