# Generated by Django 5.1.7 on 2025-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
