# Generated by Django 5.1.7 on 2025-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_teacherprofile_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
